/*
    JHilbert, a verifier for collaborative theorem proving
    Copyright © 2008 Alexander Klauer

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

    You may contact the author on these Wiki pages:
    http://planetx.cc.vt.edu/AsteroidMeta//GrafZahl (preferred)
    http://en.wikisource.org/wiki/User_talk:GrafZahl
*/

package jhilbert.util;

import jhilbert.exceptions.GeneralException;
import jhilbert.util.Scanner;

/**
 * Exception generated by a {@link Scanner} object.
 */
public final class ScannerException extends GeneralException {

	/**
	 * Constructs a new ScannerException with the specified detail message, a context taken from Scanner#getContext()
	 * and the specified cause.
	 *
	 * @param message detail message String.
	 * @param scanner Scanner which raised this exception (must not be <code>null</code>).
	 * @param cause the Throwable which caused this exception.
	 *
	 * @throws NullPointerException if scanner is <code>null</code>.
	 */
	public ScannerException(final String message, final Scanner scanner, final Throwable cause) {
		super(message, scanner.getClass().toString() + ": " + scanner.getContextString(), cause);
	}

	/**
	 * Constructs a new ScannerException with the specified detail message and a context taken from
	 * Scanner#getContext().
	 *
	 * @param message detail message String.
	 * @param scanner Scanner which raised this exception.
	 *
	 * @throws NullPointerException if scanner is <code>null</code>.
	 */
	public ScannerException(final String message, final Scanner scanner) {
		this(message, scanner, null);
	}

}
