package jhilbert.exceptions;

import jhilbert.exceptions.GeneralException;
import jhilbert.util.Scanner;

/**
 * Exception generated by a {@link Scanner} object.
 */
public final class ScannerException extends GeneralException {

	/**
	 * Constructs a new ScannerException with the specified detail message, a context taken from Scanner#getContext()
	 * and the specified cause.
	 *
	 * @param message detail message String.
	 * @param scanner Scanner which raised this exception (must not be <code>null</code>).
	 * @param cause the Throwable which caused this exception.
	 *
	 * @throws NullPointerException if scanner is <code>null</code>.
	 */
	public ScannerException(final String message, final Scanner scanner, final Throwable cause) {
		super(message, scanner.getClass().toString() + ": " + scanner.getContextString(), cause);
	}

	/**
	 * Constructs a new ScannerException with the specified detail message and a context taken from
	 * Scanner#getContext().
	 *
	 * @param message detail message String.
	 * @param scanner Scanner which raised this exception.
	 *
	 * @throws NullPointerException if scanner is <code>null</code>.
	 */
	public ScannerException(final String message, final Scanner scanner) {
		this(message, scanner, null);
	}

}
